title: Route4Me API Docs
author: Route4Me
email: support@route4me.com
description: > # this means to ignore newlines until "baseurl:"
  The quick brown fox jumps over the lazy dog.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: false # set to false to remove excerpts on the homepage

#theme: jekyll-theme-midnight
theme: minima
